### ISSUE TITLE
UUID's are of type String.

### ISSUE THREAD

**Issue by sanketdpm** [sushilisfine/ScaleSampark#1]
https://en.wikipedia.org/wiki/Universally_unique_identifier

Accordingly, can you ensure UUID's are generated, stored and returned as described in document.

https://github.com/sushilisfine/ScaleSampark/blob/9c6d82bf7fa829323bab4a76609f912454e794b7/ScaleSampark/src/main/java/com/chatbox/scalesampark/entity/user/User.java#L44

**Comment by sushilisfine** [comment]
UUID's are created of type string and are generated for User and Message both.
