### ISSUE TITLE
Should we have a field to capture name of Message Type

### ISSUE THREAD

**Issue by sanketdpm** [sushilisfine/ScaleSampark#3]
MessageType has an auto-incrementing ID as well as a Message Type field. However should we have a field to capture name of Message Type as well? Ex: ID: 1, Name: Text; ID: 2, Name: JPG; etc... What are your thoughts?

https://github.com/sushilisfine/ScaleSampark/blob/9c6d82bf7fa829323bab4a76609f912454e794b7/ScaleSampark/src/main/java/com/chatbox/scalesampark/entity/message/MessageType.java#L39

**Comment by sushilisfine** [comment]
Now we have a message id and a Message Type field to capture message types.
