### ISSUE TITLE
UC-02 not satisfied

### ISSUE THREAD

**Issue by sanketdpm** [sushilisfine/ScaleSampark#4]
"Entire participant list is sent back as response to this request"

https://github.com/sushilisfine/ScaleSampark/blob/9c6d82bf7fa829323bab4a76609f912454e794b7/ScaleSampark/src/main/java/com/chatbox/scalesampark/controller/RegistrationController.java#L63

**Comment by sanketdpm** [comment]
Expected is: 

/v1/participants/{uuid} --> returns details of participant indicated by {uuid}

/v1/participants --> returns details of all participants

**Comment by sushilisfine** [comment]
Now we have two API's :
/v1/participants/{UUID} --> returns details of participant indicated by {UUID}

/v1/participants --> returns details of all participants
