### ISSUE TITLE
Performance: expensive operation

### ISSUE THREAD

**Issue by sanketdpm** [sushilisfine/ScaleSampark#5]
Is it possible to do the prepareSecreteKey routine only at time of initializing the bean?

https://github.com/sushilisfine/ScaleSampark/blob/9c6d82bf7fa829323bab4a76609f912454e794b7/ScaleSampark/src/main/java/com/chatbox/scalesampark/service/utility/AESEncryptionDecryption.java#L25

**Comment by sushilisfine** [comment]
prepareSecreteKey(String myKey)  method now only called at the time of bean creation.
