### ISSUE TITLE
UC-04: assumption contradicts UC needs

### ISSUE THREAD

**Issue by sanketdpm** [sushilisfine/ScaleSampark#6]
UC-04/3: All messages received in system **since the last time this user** fetched pending message(s) is(are) retrieved from persistent storage

Assumption 2: If message is pooled by any of the present user, changed the status of message from unread to read of all the pending messages.

Assumption is contradictory to a clearly specified need of system. Can you please overcome this contradiction?

**Comment by sushilisfine** [comment]
Now user's last seen is updated just after new message is created and also when a user polls pending messages.
A user will now be able to see all the messages that are pending after the user has last seen.
