### ISSUE TITLE
Best Practices: RESTful nomenclature

### ISSUE THREAD

**Issue by sanketdpm** [sushilisfine/ScaleSampark#7]
Root resource should be named plural and HTTP verbs act on resource(s). Examples:
POST: /api/v1/participants --> to create a new participant
GET: /api/v1/participants --> to get all participants
DELETE: /api/v1/participants/{uuid} --> deletes the specified participant

Use query params to filter resource(s). Example:
GET: /api/v1/messages?uuid={user_uuid} --> returns all pending messages for user_uuid

Can you look for these in your API and make appropriate changes?

**Comment by sushilisfine** [comment]
Changes made as per Rest nomenclature and best practice.
